services:
  binexp-poison-in-the-wells-4:
    image: git.ctf.umanitobacssa.ca/cssa/binexp-poison-in-the-wells-4:latest
    container_name: binexp-poison-in-the-wells-4
    ports:
      - "30204:22"
    restart: unless-stopped
    # security_opt:
    #   - seccomp:seccomp.json  # Enable syscall restrictions
