version: "3.8"

services:
  be-bufferoverflow-2:
    build: .
    container_name: be-bufferoverflow-2
    ports:
      - "30202:22"
    restart: unless-stopped
    # security_opt:
    #   - seccomp:seccomp.json  # Enable syscall restrictions
