version: "3.8"

services:
  be-bufferoverflow-3:
    build: .
    container_name: be-bufferoverflow-3
    ports:
      - "30203:22"
    restart: unless-stopped
    # security_opt:
    #   - seccomp:seccomp.json  # Enable syscall restrictions
