services:
  binexp-poison-in-the-wells-3:
    image: git.ctf.umanitobacssa.ca/cssa/binexp-poison-in-the-wells-3:latest
    container_name: binexp-poison-in-the-wells-3
    ports:
      - "30203:22"
    restart: unless-stopped
    # security_opt:
    #   - seccomp:seccomp.json  # Enable syscall restrictions
